# Generated by Django 6.0.1 on 2026-02-11 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, choices=[('home_based_elderly_care', 'Home-Based Elderly Care'), ('hospital_support_care', 'Hospital Support Care'), ('free_medical_outreach', 'Free Medical Outreach'), ('caregiver_training', 'Caregiver Training'), ('international_career_preparation', 'International Career Preparation'), ('professional_certification', 'Professional Certification')], max_length=255, null=True)),
                ('caregiver_experience', models.CharField(blank=True, choices=[('elderly_care_specialist', 'Elderly Care Specialist'), ('nursing_assistant', 'Nursing Assistant'), ('companion_care', 'Companion Care')], max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
