# Generated by Django 6.0.1 on 2026-02-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment_special_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='special_request',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
