# Generated by Django 6.0.1 on 2026-02-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_appointment_special_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='caregiver_experience',
            field=models.CharField(blank=True, choices=[('___', 'Preferred Caregiving Experience'), ('elderly_care_specialist', 'Elderly Care Specialist'), ('nursing_assistant', 'Nursing Assistant'), ('companion_care', 'Companion Care')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(blank=True, choices=[('___', 'Service'), ('home_based_elderly_care', 'Home-Based Elderly Care'), ('hospital_support_care', 'Hospital Support Care'), ('free_medical_outreach', 'Free Medical Outreach'), ('caregiver_training', 'Caregiver Training'), ('international_career_preparation', 'International Career Preparation'), ('professional_certification', 'Professional Certification')], max_length=255, null=True),
        ),
    ]
